version: "3.9"

networks:
  db-net:

services:
  db-mysql:
    image: mariadb:10.5.10
    container_name: "${DB_CONTAINER_NAME}"
    ports:
      - ${MYSQL_PORT}:3306
    expose:
      - ${MYSQL_PORT}
    volumes:
      - ../database/files:/var/lib/mysql
      - ../database/dump:/var/lib/mysqldump
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    #restart: always # always restart unless stopped manually
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - db-net